# Generated by Django 3.0 on 2022-09-26 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_on', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.PositiveIntegerField(blank=True, choices=[(1, 'NORMAL SERVICE'), (2, 'CUSTOM')], default=1, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_pet_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('pet_gender', models.PositiveIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('vet_name', models.CharField(blank=True, max_length=150, null=True)),
                ('vet_email', models.CharField(blank=True, max_length=100, null=True)),
                ('add_note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('vet_profile', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('vet_number', models.CharField(blank=True, max_length=12, null=True)),
                ('vet_adrress', models.CharField(blank=True, max_length=500, null=True)),
                ('vaccines', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ManyToManyField(to='enduser.Images')),
                ('pet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enduser.PetType')),
            ],
            options={
                'db_table': 'tbl_pet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('complain', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[(0, 'NotAssigned'), (1, 'Assigned')], default=0, max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_helprequest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favourite', models.BooleanField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_by', to=settings.AUTH_USER_MODEL)),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_favourite_rvt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=150, null=True)),
                ('cvv', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=-1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_image/')),
                ('default', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[(1, 'Visa'), (2, 'Mastercard')], max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_card',
                'managed': True,
            },
        ),
    ]
